---
title: "IS"
author: "Yildiz"
date: "03 11 2020"
output: html_document
---

---
title: "IS"
author: "Yildiz"
date: "02 11 2020"
output: html_document
---

```{r}
library(haven)
library(ggplot2)
library(tidyverse)
library(stargazer)
library(dplyr)
library(readxl)
```



```{r}
sDataFile <- "data/colonial.dta"
sZipURL <-"https://lawrenceu-my.sharepoint.com/:u:/g/personal/lhostj_lawrence_edu/ETpCQvMEu7tJmcNzJ8vdHnoBqepoCReca2xEtfekDvq2nQ?download=1"

if(!dir.exists("data")){
  dir.create("data")
}
if(!file.exists(sDataFile)) {
  download.file(url = sZipURL, destfile = "data/temp.zip", mode = "wb")
  unzip("data/temp.zip", exdir = "data", junkpaths = TRUE)
  file.remove("data/temp.zip")
}


colonial <- read_dta(sDataFile)
```

```{r}
View(colonial)
```

```{r}
colonial64 <- colonial %>% filter(baseSample == 1)
```

```{r}
view(colonial64)
```

```{r}
colonial61 <- colonial64 %>% slice(-c(6,20,62))
```

```{r}
view(colonial61)
```

```{r}
colonial58 <- colonial61 %>% slice(-c(10,30,61))
view(colonial58)
```

```{r}
weil_data <- read_excel("weil data.xlsx", sheet = "Sayfa1")
weil_data1 <- weil_data %>% rename(CodeCO = `WDI Code`)
```

```{r}
IS_table <- merge(x = colonial58, y = weil_data1[ , c("CodeCO", "corrcon09", "instability")], by = "CodeCO", all.x=TRUE)
```
```{r}
view(IS_table)
```



